### ISSUE TITLE
Update 200PU configuration

### ISSUE THREAD

**Issue by sitongan** [CMS-HGCAL/reco-prodtools#79] opened 2019-08-27 08:59 UTC
I was attempting to produce some events with the latest pileup configuration in produceSkeletons_D41_NoSmear_PU_AVE_200_BX_25ns.sh and got the error of:

Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/2C56BC73-5687-674C-8684-6C785A88DB78.root

and indeed this directory is empty. I’m assuming that the config script needs to be updated to point to the latest MinBias mixing files here:

/eos/cms/store/relval/CMSSW_11_0_0_pre6/

but there are two directories marked with MinBias:

RelValMinBiasFS_13_UP18_ForMixing/
RelValMinBias_13/

and I can’t be 100% sure which file to use. Could you kindly look into this issue?

**Comment by riga** [comment] 2019-08-27 09:45
Hi @sitongan,
thanks for reporting. I will check what's in the official workflow later!

**Comment by riga** [comment] 2019-08-27 11:23
For the setup with PU 200, the prodtools use workflow 20634.0 (TTbar_14TeV_TuneCUETP8M1_2026D41PU_GenSimHLBeamSpotFull14+DigiFullTriggerPU_2026D41PU+RecoFullGlobalPU_2026D41PU+HARVESTFullGlobalPU_2026D41PU), which is configured to include pileup from `/RelValMinBias_14TeV/CMSSW_10_6_0_patch2-106X_upgrade2023_realistic_v3_2023D41noPU-v1/GEN-SIM` and the directories on eos are in fact all empty.

The best solution is probably to directly ask PdmV for a recommendation.

**Comment by riga** [comment] 2019-08-28 14:37
Hey,
ehm, can you try to create a proxy first (`voms-proxy-init`)?
The `cmsDriver.py` command internally communicates with DAS to get the file names of the LFN passed to the `--pileup_input` option. And for that step, it requires a valid proxy. Unfortunately, it does not throw a verbose error in case the proxy is missing.

Also, as you can see [here](https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FRelValMinBias_14TeV%2FCMSSW_10_6_0_patch2-106X_upgrade2023_realistic_v3_2023D41noPU-v1%2FGEN-SIM), the dataset is only stored physically at three US tiers, so you wouldn't be able to find it "locally" on the CERN CMS EOS space.

**Comment by sitongan** [comment] 2019-08-28 15:21
Hi Marcel,

**Same error persists:**

WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
condor_exec.exe: line 21: CMSSW_11_0_0_pre6: command not found
28-Aug-2019 17:10:28 CEST  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root
%MSG-w XrdAdaptorInternal:  MixingModule:mix@ctor 28-Aug-2019 17:10:30 CEST  pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root.
%MSG
%MSG-w XrdAdaptorInternal:  MixingModule:mix@ctor 28-Aug-2019 17:10:30 CEST  pre-events
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=.
%MSG
28-Aug-2019 17:10:30 CEST  Fallback request to file root://xrootd-cms.infn.it//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root
secgsi: error getting user proxies
[2019-08-28 17:10:36.979652 +0200][Error  ][XRootDTransport   ] [xrootd.rcac.purdue.edu:1094 #0.0] No protocols left to try
[2019-08-28 17:10:36.979713 +0200][Error  ][AsyncSock         ] [xrootd.rcac.purdue.edu:1094 #0.0] Socket error while handshaking: [FATAL] Auth failed
[2019-08-28 17:10:36.979839 +0200][Error  ][PostMaster        ] [xrootd.rcac.purdue.edu:1094 #0] elapsed = 0, pConnectionWindow = 31 seconds.
[2019-08-28 17:10:36.979861 +0200][Error  ][PostMaster        ] [xrootd.rcac.purdue.edu:1094 #0] Unable to recover: [FATAL] Auth failed.
[2019-08-28 17:10:36.979885 +0200][Error  ][XRootD            ] [xrootd.rcac.purdue.edu:1094] Impossible to send message kXR_open (file: /store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it, mode: 0460, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  MixingModule:mix@ctor 28-Aug-2019 17:13:26 CEST  pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it.
%MSG
secgsi: error getting user proxies
[2019-08-28 17:13:27.161245 +0200][Error  ][XRootDTransport   ] [xrootd-local.unl.edu:1094 #0.0] No protocols left to try
[2019-08-28 17:13:27.161277 +0200][Error  ][AsyncSock         ] [xrootd-local.unl.edu:1094 #0.0] Socket error while handshaking: [FATAL] Auth failed
[2019-08-28 17:13:27.161380 +0200][Error  ][PostMaster        ] [xrootd-local.unl.edu:1094 #0] elapsed = 1, pConnectionWindow = 31 seconds.
[2019-08-28 17:13:27.161400 +0200][Error  ][PostMaster        ] [xrootd-local.unl.edu:1094 #0] Unable to recover: [FATAL] Auth failed.
[2019-08-28 17:13:27.161411 +0200][Error  ][XRootD            ] [xrootd-local.unl.edu:1094] Impossible to send message kXR_open (file: /store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it,, mode: 0660, flags: kXR_open_read kXR_async kXR_retstat ). Trying to recover.
%MSG-w XrdAdaptorInternal:  MixingModule:mix@ctor 28-Aug-2019 17:16:22 CEST  pre-events
Failed to open file at URL root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it,.
%MSG
----- Begin Fatal Exception 28-Aug-2019 17:16:22 CEST-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling XrdFile::open()
Exception Message:
Failed to open the file 'root://xrootd-cms.infn.it//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root'
   Additional Info:
      [a] XrdCl::File::Open(name='root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root', flags=0x10, permissions=0660) => error '[ERROR] Server responded with an error: [3011] Unable to open file /eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root; No such file or directory
' (errno=3011, code=400). No additional data servers were found.
      [b] Last URL tried: root://eoscms.cern.ch:1094//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=
      [c] Problematic data server: eoscms.cern.ch:1094
      [d] Disabled source: eoscms.cern.ch:1094
      [e] Input file root://eoscms.cern.ch//eos/cms/store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root could not be opened.
Fallback Input file root://xrootd-cms.infn.it//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root also could not be opened.
Original exception info is above; fallback exception info is below.
      [f] XrdCl::File::Open(name='root://xrootd-cms.infn.it//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root', flags=0x10, permissions=0660) => error '[ERROR] Operation expired' (errno=0, code=206). No additional data servers were found.
      [g] Last URL tried: root://cms-xrd-global.cern.ch:1094//store/relval/CMSSW_10_6_0_patch2/RelValMinBias_14TeV/GEN-SIM/106X_upgrade2023_realistic_v3_2023D41noPU-v1/10000/F806295A-492F-EF4F-9D91-15DA8769DD72.root?tried=+1213xrootd-cms-redir-01.cr.cnaf.infn.it,
      [h] Problematic data server: cms-xrd-global.cern.ch:1094
      [i] Disabled source: cms-xrd-global.cern.ch:1094
----- End Fatal Exception -------------------------------------------------
xrdcp: No such file or directory processing *GSD*.root

**proxy init:**

$ voms-proxy-init --rfc --voms cms
Enter GRID pass phrase for this identity:
Contacting lcg-voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "cms"...
Remote VOMS server contacted succesfully.


Created proxy in /tmp/x509up_u115645.

Your proxy is valid until Thu Aug 29 05:05:06 CEST 2019

maybe my proxy is not configured correctly?

**Comment by riga** [comment] 2019-08-28 19:03
> Update: I can access the file via ROOT and xrootd OK. Maybe there's some problem with condor configuration?

Looks like. The second line, `condor_exec.exe: line 21: CMSSW_11_0_0_pre6: command not found`, already looks suspicious. Which `SCRAM_ARCH` do you use?

Also, can you try creating a proxy without rfc compliance?

**Comment by sitongan** [comment] 2019-08-29 11:30
slc7_amd64_gcc700
Attempted proxy without rfc - the same error persists.
Also when I use the no PU configuration everything works fine.

**Comment by riga** [comment] 2019-08-29 12:30
> Also when I use the no PU configuration everything works fine.

Without PU, there is no need for communicating with DAS and for streaming files over XRootD. The latter is causing the error you see. I will try to reproduce that another time later today, maybe it is sth temporary.

**Comment by riga** [comment] 2019-09-06 11:12
Hi @sitongan ,
it was in fact a proxy problem on htcondor. I just added the forwarding of the proxy to the [prodtools branch of the hgcalsim]() repository. Can you try this command on a fresh checkout?

```
law run sim.GSDTask \
  --version proxytest \
  --nevts 1 --gunMode closebydr --partID 22,22,22,22 \
  --thresholdMin 1 --thresholdMax 100 --zMin 319 --zMax 319 --rMin 0 --rMax 0.4 \
  --n-tasks 1 --workflow htcondor --max-runtime 1.0
```

**Comment by sitongan** [comment] 2019-09-10 10:01
Hi @riga,

Seems to be working - After adding --local-scheduler the command successfully run to completion generating a 1.6M root file from the GSD task. However I have no means of validating this. Let me try to run a full simulation workflow up until NTUP and get back to you.

**Comment by riga** [comment] 2019-09-16 11:50
Hey @sitongan , any updates on your checks?
I will close the issue for now. If the PU configuration is still not working for you, we can of course reopen.

**Closed by riga** 2019-09-16 11:50 UTC
Labels: help wanted
